/* tslint:disable */
/* eslint-disable */
/**
 * CatalogService
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

export interface MenuItems {
    'id'?: number;
    'restaurant_id'?: number;
    'item_name'?: string | null;
    'price_cents'?: number;
    'available'?: boolean;
    'description'?: string | null;
    'tags'?: string | null;
}

/**
 * CatalogServiceApi - axios parameter creator
 */
export const CatalogServiceApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getHealth: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/catalog/health`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * CatalogServiceApi - functional programming interface
 */
export const CatalogServiceApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = CatalogServiceApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getHealth(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getHealth(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CatalogServiceApi.getHealth']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * CatalogServiceApi - factory interface
 */
export const CatalogServiceApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = CatalogServiceApiFp(configuration)
    return {
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getHealth(options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.getHealth(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * CatalogServiceApi - object-oriented interface
 */
export class CatalogServiceApi extends BaseAPI {
    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getHealth(options?: RawAxiosRequestConfig) {
        return CatalogServiceApiFp(this.configuration).getHealth(options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * MenuApi - axios parameter creator
 */
export const MenuApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {number} [restaurantId] 
         * @param {Array<MenuItems>} [menuItems] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiCatalogBulkPost: async (restaurantId?: number, menuItems?: Array<MenuItems>, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/catalog/bulk`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (restaurantId !== undefined) {
                localVarQueryParameter['restaurantId'] = restaurantId;
            }

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'text/plain,application/json,text/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(menuItems, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {number} [restaurantId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiCatalogDelete: async (restaurantId?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/catalog`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (restaurantId !== undefined) {
                localVarQueryParameter['restaurantId'] = restaurantId;
            }


            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {number} [restaurantId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiCatalogGet: async (restaurantId?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/catalog`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (restaurantId !== undefined) {
                localVarQueryParameter['restaurantId'] = restaurantId;
            }

            localVarHeaderParameter['Accept'] = 'text/plain,application/json,text/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {number} itemId 
         * @param {number} [restaurant] 
         * @param {boolean} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiCatalogItemIdAvailabilityPut: async (itemId: number, restaurant?: number, body?: boolean, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'itemId' is not null or undefined
            assertParamExists('apiCatalogItemIdAvailabilityPut', 'itemId', itemId)
            const localVarPath = `/api/catalog/{itemId}/availability`
                .replace(`{${"itemId"}}`, encodeURIComponent(String(itemId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (restaurant !== undefined) {
                localVarQueryParameter['restaurant'] = restaurant;
            }

            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(body, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {number} itemId 
         * @param {number} [restaurant] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiCatalogItemIdDelete: async (itemId: number, restaurant?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'itemId' is not null or undefined
            assertParamExists('apiCatalogItemIdDelete', 'itemId', itemId)
            const localVarPath = `/api/catalog/{itemId}`
                .replace(`{${"itemId"}}`, encodeURIComponent(String(itemId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (restaurant !== undefined) {
                localVarQueryParameter['restaurant'] = restaurant;
            }


            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {number} itemId 
         * @param {number} [restaurant] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiCatalogItemIdGet: async (itemId: number, restaurant?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'itemId' is not null or undefined
            assertParamExists('apiCatalogItemIdGet', 'itemId', itemId)
            const localVarPath = `/api/catalog/{itemId}`
                .replace(`{${"itemId"}}`, encodeURIComponent(String(itemId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (restaurant !== undefined) {
                localVarQueryParameter['restaurant'] = restaurant;
            }

            localVarHeaderParameter['Accept'] = 'text/plain,application/json,text/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {number} itemId 
         * @param {number} [restaurant] 
         * @param {MenuItems} [menuItems] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiCatalogItemIdPut: async (itemId: number, restaurant?: number, menuItems?: MenuItems, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'itemId' is not null or undefined
            assertParamExists('apiCatalogItemIdPut', 'itemId', itemId)
            const localVarPath = `/api/catalog/{itemId}`
                .replace(`{${"itemId"}}`, encodeURIComponent(String(itemId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (restaurant !== undefined) {
                localVarQueryParameter['restaurant'] = restaurant;
            }

            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(menuItems, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {number} [restaurant] 
         * @param {MenuItems} [menuItems] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiCatalogPost: async (restaurant?: number, menuItems?: MenuItems, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/catalog`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (restaurant !== undefined) {
                localVarQueryParameter['restaurant'] = restaurant;
            }

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'text/plain,application/json,text/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(menuItems, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * MenuApi - functional programming interface
 */
export const MenuApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = MenuApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {number} [restaurantId] 
         * @param {Array<MenuItems>} [menuItems] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiCatalogBulkPost(restaurantId?: number, menuItems?: Array<MenuItems>, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<MenuItems>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiCatalogBulkPost(restaurantId, menuItems, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['MenuApi.apiCatalogBulkPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {number} [restaurantId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiCatalogDelete(restaurantId?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiCatalogDelete(restaurantId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['MenuApi.apiCatalogDelete']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {number} [restaurantId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiCatalogGet(restaurantId?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<MenuItems>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiCatalogGet(restaurantId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['MenuApi.apiCatalogGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {number} itemId 
         * @param {number} [restaurant] 
         * @param {boolean} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiCatalogItemIdAvailabilityPut(itemId: number, restaurant?: number, body?: boolean, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiCatalogItemIdAvailabilityPut(itemId, restaurant, body, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['MenuApi.apiCatalogItemIdAvailabilityPut']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {number} itemId 
         * @param {number} [restaurant] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiCatalogItemIdDelete(itemId: number, restaurant?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiCatalogItemIdDelete(itemId, restaurant, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['MenuApi.apiCatalogItemIdDelete']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {number} itemId 
         * @param {number} [restaurant] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiCatalogItemIdGet(itemId: number, restaurant?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<MenuItems>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiCatalogItemIdGet(itemId, restaurant, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['MenuApi.apiCatalogItemIdGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {number} itemId 
         * @param {number} [restaurant] 
         * @param {MenuItems} [menuItems] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiCatalogItemIdPut(itemId: number, restaurant?: number, menuItems?: MenuItems, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiCatalogItemIdPut(itemId, restaurant, menuItems, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['MenuApi.apiCatalogItemIdPut']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {number} [restaurant] 
         * @param {MenuItems} [menuItems] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiCatalogPost(restaurant?: number, menuItems?: MenuItems, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<MenuItems>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiCatalogPost(restaurant, menuItems, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['MenuApi.apiCatalogPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * MenuApi - factory interface
 */
export const MenuApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = MenuApiFp(configuration)
    return {
        /**
         * 
         * @param {number} [restaurantId] 
         * @param {Array<MenuItems>} [menuItems] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiCatalogBulkPost(restaurantId?: number, menuItems?: Array<MenuItems>, options?: RawAxiosRequestConfig): AxiosPromise<Array<MenuItems>> {
            return localVarFp.apiCatalogBulkPost(restaurantId, menuItems, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {number} [restaurantId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiCatalogDelete(restaurantId?: number, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.apiCatalogDelete(restaurantId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {number} [restaurantId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiCatalogGet(restaurantId?: number, options?: RawAxiosRequestConfig): AxiosPromise<Array<MenuItems>> {
            return localVarFp.apiCatalogGet(restaurantId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {number} itemId 
         * @param {number} [restaurant] 
         * @param {boolean} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiCatalogItemIdAvailabilityPut(itemId: number, restaurant?: number, body?: boolean, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.apiCatalogItemIdAvailabilityPut(itemId, restaurant, body, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {number} itemId 
         * @param {number} [restaurant] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiCatalogItemIdDelete(itemId: number, restaurant?: number, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.apiCatalogItemIdDelete(itemId, restaurant, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {number} itemId 
         * @param {number} [restaurant] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiCatalogItemIdGet(itemId: number, restaurant?: number, options?: RawAxiosRequestConfig): AxiosPromise<MenuItems> {
            return localVarFp.apiCatalogItemIdGet(itemId, restaurant, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {number} itemId 
         * @param {number} [restaurant] 
         * @param {MenuItems} [menuItems] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiCatalogItemIdPut(itemId: number, restaurant?: number, menuItems?: MenuItems, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.apiCatalogItemIdPut(itemId, restaurant, menuItems, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {number} [restaurant] 
         * @param {MenuItems} [menuItems] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiCatalogPost(restaurant?: number, menuItems?: MenuItems, options?: RawAxiosRequestConfig): AxiosPromise<MenuItems> {
            return localVarFp.apiCatalogPost(restaurant, menuItems, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * MenuApi - object-oriented interface
 */
export class MenuApi extends BaseAPI {
    /**
     * 
     * @param {number} [restaurantId] 
     * @param {Array<MenuItems>} [menuItems] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public apiCatalogBulkPost(restaurantId?: number, menuItems?: Array<MenuItems>, options?: RawAxiosRequestConfig) {
        return MenuApiFp(this.configuration).apiCatalogBulkPost(restaurantId, menuItems, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {number} [restaurantId] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public apiCatalogDelete(restaurantId?: number, options?: RawAxiosRequestConfig) {
        return MenuApiFp(this.configuration).apiCatalogDelete(restaurantId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {number} [restaurantId] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public apiCatalogGet(restaurantId?: number, options?: RawAxiosRequestConfig) {
        return MenuApiFp(this.configuration).apiCatalogGet(restaurantId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {number} itemId 
     * @param {number} [restaurant] 
     * @param {boolean} [body] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public apiCatalogItemIdAvailabilityPut(itemId: number, restaurant?: number, body?: boolean, options?: RawAxiosRequestConfig) {
        return MenuApiFp(this.configuration).apiCatalogItemIdAvailabilityPut(itemId, restaurant, body, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {number} itemId 
     * @param {number} [restaurant] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public apiCatalogItemIdDelete(itemId: number, restaurant?: number, options?: RawAxiosRequestConfig) {
        return MenuApiFp(this.configuration).apiCatalogItemIdDelete(itemId, restaurant, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {number} itemId 
     * @param {number} [restaurant] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public apiCatalogItemIdGet(itemId: number, restaurant?: number, options?: RawAxiosRequestConfig) {
        return MenuApiFp(this.configuration).apiCatalogItemIdGet(itemId, restaurant, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {number} itemId 
     * @param {number} [restaurant] 
     * @param {MenuItems} [menuItems] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public apiCatalogItemIdPut(itemId: number, restaurant?: number, menuItems?: MenuItems, options?: RawAxiosRequestConfig) {
        return MenuApiFp(this.configuration).apiCatalogItemIdPut(itemId, restaurant, menuItems, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {number} [restaurant] 
     * @param {MenuItems} [menuItems] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public apiCatalogPost(restaurant?: number, menuItems?: MenuItems, options?: RawAxiosRequestConfig) {
        return MenuApiFp(this.configuration).apiCatalogPost(restaurant, menuItems, options).then((request) => request(this.axios, this.basePath));
    }
}



